### ISSUE TITLE
broken calendar

### ISSUE THREAD

**Issue by bacarini** [locaweb/locawebstyle-v1#37]
![screen shot 2015-02-03 at 10 45 20 am](https://cloud.githubusercontent.com/assets/4749909/6021089/1be77c36-ab9a-11e4-9d56-6d5d6a1f9d7d.png)

**Comment by deividmarques** [comment]
Conforme conversei com o @bacarini, identificamos que  esse problema ocorre devido ao CSS interno do Painel e NÃO no framework.
Podemos conferir a documentação online e atualizada, está tudo perfeito e sem quebra de layout:
http://locaweb.github.io/locawebstyle-v1/manual/formularios/campos/
